version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: db
    hostname: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - default
    env_file:
      - src/.env
    ports:
      - "5432:5432"

  api:
    build: .
    env_file:
      - src/.env
    container_name: api
    networks:
      - default
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./migrations/versions:/app/migrations/versions

volumes:
  data:
    driver: local
