"""'rename_id_field'

Revision ID: f493877df7d1
Revises: b049410df4bb
Create Date: 2023-02-03 18:25:26.406024

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f493877df7d1'
down_revision = 'b049410df4bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accountoperation', sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.drop_index('ix_accountoperation_account_operation_id', table_name='accountoperation')
    op.create_index(op.f('ix_accountoperation_id'), 'accountoperation', ['id'], unique=False)
    op.drop_column('accountoperation', 'account_operation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accountoperation', sa.Column('account_operation_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_accountoperation_id'), table_name='accountoperation')
    op.create_index('ix_accountoperation_account_operation_id', 'accountoperation', ['account_operation_id'], unique=False)
    op.drop_column('accountoperation', 'id')
    # ### end Alembic commands ###
